<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chugiamdan</name>
   <tag></tag>
   <elementGuidId>7c9c443c-3f84-4976-98cc-cd3b059cdf5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.product-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh sách'])[1]/following::h3[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>1f0211bf-3878-4394-b795-8277aac908cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-name</value>
      <webElementGuid>ed782eb7-e9d2-434c-90bf-537e4d7f001c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hộp gỗ có khóa bộ 4 cái</value>
      <webElementGuid>3548a22e-52d5-40f8-ad94-e6e9f6ff2d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container main-collection&quot;]/div[@class=&quot;row&quot;]/section[@class=&quot;main_container collection col-lg-9 col-lg-push-3&quot;]/div[@class=&quot;category-products products&quot;]/section[@class=&quot;products-view products-view-grid&quot;]/div[@class=&quot;row row-gutter-14&quot;]/div[@class=&quot;col-xs-6 col-xss-6 col-sm-4 col-md-4 col-lg-4&quot;]/div[@class=&quot;product-box&quot;]/div[@class=&quot;product-info a-center&quot;]/h3[@class=&quot;product-name&quot;]</value>
      <webElementGuid>58e76628-72a4-4f01-8c11-d12e36d9165d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh sách'])[1]/following::h3[1]</value>
      <webElementGuid>dcfba9bb-e84c-4898-a354-a136334699f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lưới'])[1]/following::h3[1]</value>
      <webElementGuid>fd448055-8220-4e01-966a-b17206353e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>75dc85a4-9c94-4d1f-827b-cf1bb59b1a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Hộp gỗ có khóa bộ 4 cái' or . = 'Hộp gỗ có khóa bộ 4 cái')]</value>
      <webElementGuid>abfde6f8-5254-466a-b7cc-2c217deb53aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
