<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputemail</name>
   <tag></tag>
   <elementGuidId>3cd58e3e-0581-45da-bef3-c072d3c7d113</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customer_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>679539b9-4d2f-43ef-9d79-f820979c3dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>7bba761d-69b3-475b-ac25-e455ae205ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-lg</value>
      <webElementGuid>504bca5a-56b1-4f16-9aaf-ef4b3aea2088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>eaee2cf9-392a-4aca-9b82-eaa5ae5415c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer_email</value>
      <webElementGuid>12fc4ba8-2a4a-425c-b664-b117af2dee77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>ea3806ae-18e4-4c61-9f9d-6d1f85fe8fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_email&quot;)</value>
      <webElementGuid>bb52f8cf-5fe5-4b08-93ef-02a24167b5dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer_email']</value>
      <webElementGuid>2556dd58-ceac-4f98-af45-a30da2188357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customer_login']/div[2]/fieldset/input</value>
      <webElementGuid>e2fed92f-992b-4fba-8cb7-a475f40eee90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/input</value>
      <webElementGuid>657b25b4-d7b5-4a84-82aa-6953ce5bba93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email' and @id = 'customer_email' and @placeholder = 'Email']</value>
      <webElementGuid>9bcf251e-a2d6-4d85-bb64-89066e29b819</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
