<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputgui</name>
   <tag></tag>
   <elementGuidId>b1f86c2b-1743-4185-bf54-f8a312a842e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.action_bottom > input.btn.btn-primary.btn-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Gửi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af8882af-d7a7-4548-9b74-673edd1ad5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-full</value>
      <webElementGuid>8acc9b23-3627-470d-88cf-71b5666057be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7d7de580-1d0b-4224-83c1-9149a4ce7c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Gửi</value>
      <webElementGuid>04456ab4-0fce-4964-aa90-3eedcc69fbc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recover_customer_password&quot;)/div[@class=&quot;action_bottom&quot;]/input[@class=&quot;btn btn-primary btn-full&quot;]</value>
      <webElementGuid>52ea18f3-0fc5-4af5-9e02-9d28f7571227</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Gửi']</value>
      <webElementGuid>6011d293-dcc4-4a53-8758-4d5b963d6b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='recover_customer_password']/div[3]/input</value>
      <webElementGuid>9ee027cd-17d7-4855-a879-096e8cbd85bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>6740801e-6d90-474e-97dc-631a48e7afa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>6bfc2057-b55a-41a2-b611-1e05a5e59018</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
