<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Z  A</name>
   <tag></tag>
   <elementGuidId>f13c3687-7abd-4aa5-941e-bd03cb947449</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.ul_2 > li:nth-of-type(3) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;sortby('alpha-desc')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d77803a5-bf61-4996-96d8-ad86d9ee5cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>9b6fb6c7-47c8-4044-986c-d38a40dc07f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>sortby('alpha-desc')</value>
      <webElementGuid>a65e264d-74ba-4a15-9dff-8d3feb195d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Z → A</value>
      <webElementGuid>0f670d42-ad4f-4617-bf50-584db28729f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sort-by&quot;)/ul[1]/li[1]/ul[@class=&quot;ul_2&quot;]/li[3]/a[1]</value>
      <webElementGuid>6ecf9b0a-2f9d-428b-82d5-fb0973476c1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;sortby('alpha-desc')&quot;]</value>
      <webElementGuid>c3654134-9357-47ba-9540-5e56ea00cd6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sort-by']/ul/li/ul/li[3]/a</value>
      <webElementGuid>5df8f66b-4e42-49b4-8d74-8e6202915876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Z → A')]</value>
      <webElementGuid>5203252f-50f1-4f95-89ff-4b7e99241ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A → Z'])[1]/following::a[1]</value>
      <webElementGuid>1296af10-b6a5-46d5-9034-21a07d2370f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mặc định'])[1]/following::a[2]</value>
      <webElementGuid>161a7df9-592f-41e5-9684-1345c04321fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giá tăng dần'])[1]/preceding::a[1]</value>
      <webElementGuid>e0de19b1-5c3a-4d37-9398-bbf3779ef1a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giá giảm dần'])[1]/preceding::a[2]</value>
      <webElementGuid>ad05281d-8efc-4fc3-bb12-92fd225b0de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Z → A']/parent::*</value>
      <webElementGuid>42d9842b-12b4-4cdd-a8f7-bd2002e9f7ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[3]</value>
      <webElementGuid>7bc22870-f5cc-4d17-b89f-e2782ee4745c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/ul/li/ul/li[3]/a</value>
      <webElementGuid>8f31d7fe-491e-43a6-8c57-bcc902db386f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Z → A' or . = 'Z → A')]</value>
      <webElementGuid>c3f9795d-2d34-4434-82c2-cf62799d1216</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
