<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Permananet Address Hung Yen</name>
   <tag></tag>
   <elementGuidId>1c6179ff-126d-4901-9949-43bac5445553</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.border.col-md-12.col-sm-12 > #permanentAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='permanentAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d6297602-5f08-46a4-9e2f-7089e097001b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>permanentAddress</value>
      <webElementGuid>cccf5613-289b-42cf-9e34-7401a0f7d538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-1</value>
      <webElementGuid>b6bafa26-71c2-41b0-b7d0-d801df8f8ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Permananet Address :Hung Yen</value>
      <webElementGuid>28c17e6a-e205-4c26-a5fe-b306a2d3dcd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;output&quot;)/div[@class=&quot;border col-md-12 col-sm-12&quot;]/p[@id=&quot;permanentAddress&quot;]</value>
      <webElementGuid>2881a4f2-16a8-4648-9538-5e03c128aea9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='permanentAddress']</value>
      <webElementGuid>348bf9d0-20d3-4173-b636-0e55a543d0ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='output']/div/p[4]</value>
      <webElementGuid>8f114ff8-21bf-40a3-ae5e-19d1d667e3fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::p[4]</value>
      <webElementGuid>43d0b0d6-faf0-40ac-945a-e39b312617b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permanent Address'])[1]/following::p[4]</value>
      <webElementGuid>c0804123-2d46-43ae-a514-ae0637cb153f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::p[1]</value>
      <webElementGuid>d4d5c1ec-88ed-4bde-9691-c3c1e8f86da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Permananet Address :']/parent::*</value>
      <webElementGuid>9959963f-fc63-4c6d-ba8a-043704d3ef96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]</value>
      <webElementGuid>5f8f8b98-787e-46fe-8883-1f7b136fbdb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'permanentAddress' and (text() = 'Permananet Address :Hung Yen' or . = 'Permananet Address :Hung Yen')]</value>
      <webElementGuid>053d5e31-2054-4131-894e-96e44626b23a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
