<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tbemailthieucham</name>
   <tag></tag>
   <elementGuidId>7a2ce2e3-9b7a-4166-a175-7f7ad9d6c0fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.errors > ul > li</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='customer_register']/div/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>84c7f2c1-1105-46bb-aeee-bbd502dbe3eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email không hợp lệ.</value>
      <webElementGuid>4da95f09-f8ac-47b5-bbca-dda880e00949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;page-login&quot;]/div[@id=&quot;login&quot;]/form[@id=&quot;customer_register&quot;]/div[@class=&quot;form-signup&quot;]/div[@class=&quot;errors&quot;]/ul[1]/li[1]</value>
      <webElementGuid>940613f5-8a67-4f12-af83-7d2cc0598173</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customer_register']/div/div/ul/li</value>
      <webElementGuid>8a0ce33e-7ad0-4b97-8bb2-7e9d9c06f99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nếu chưa có tài khoản vui lòng đăng ký tại đây'])[1]/following::li[1]</value>
      <webElementGuid>919c3a22-edd8-4028-a129-e5cd22931de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng ký tài khoản'])[1]/following::li[1]</value>
      <webElementGuid>2b8ecd2c-ee74-43ef-926b-14cb58825ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Họ:'])[1]/preceding::li[1]</value>
      <webElementGuid>e7d33ba2-5ecb-48d7-a81a-4c510ec76bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tên:'])[1]/preceding::li[1]</value>
      <webElementGuid>eb6b1e8e-0c1f-4696-acb1-dc16fafb9322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email không hợp lệ.']/parent::*</value>
      <webElementGuid>a980d194-ce77-4e23-9435-b5bd47d5a264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/ul/li</value>
      <webElementGuid>d99ff8c7-1621-4a85-a3f3-55d8fd21c3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Email không hợp lệ.' or . = 'Email không hợp lệ.')]</value>
      <webElementGuid>7f1b6d66-1d28-4091-ab2f-4e5e2135a90c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
